// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: ham-questions-pool.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sublement   string   `protobuf:"bytes,1,opt,name=sublement,proto3" json:"sublement,omitempty"`
	Sequence    int32    `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Chapter     string   `protobuf:"bytes,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Stem        string   `protobuf:"bytes,4,opt,name=stem,proto3" json:"stem,omitempty"`
	Key         string   `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	Distractors []string `protobuf:"bytes,6,rep,name=distractors,proto3" json:"distractors,omitempty"`
	Figure      string   `protobuf:"bytes,7,opt,name=figure,proto3" json:"figure,omitempty"`
}

func (x *Question) Reset() {
	*x = Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ham_questions_pool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_ham_questions_pool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_ham_questions_pool_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetSublement() string {
	if x != nil {
		return x.Sublement
	}
	return ""
}

func (x *Question) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Question) GetChapter() string {
	if x != nil {
		return x.Chapter
	}
	return ""
}

func (x *Question) GetStem() string {
	if x != nil {
		return x.Stem
	}
	return ""
}

func (x *Question) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Question) GetDistractors() []string {
	if x != nil {
		return x.Distractors
	}
	return nil
}

func (x *Question) GetFigure() string {
	if x != nil {
		return x.Figure
	}
	return ""
}

type QuestionPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question []*Question `protobuf:"bytes,1,rep,name=question,proto3" json:"question,omitempty"`
}

func (x *QuestionPool) Reset() {
	*x = QuestionPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ham_questions_pool_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionPool) ProtoMessage() {}

func (x *QuestionPool) ProtoReflect() protoreflect.Message {
	mi := &file_ham_questions_pool_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionPool.ProtoReflect.Descriptor instead.
func (*QuestionPool) Descriptor() ([]byte, []int) {
	return file_ham_questions_pool_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionPool) GetQuestion() []*Question {
	if x != nil {
		return x.Question
	}
	return nil
}

var File_ham_questions_pool_proto protoreflect.FileDescriptor

var file_ham_questions_pool_proto_rawDesc = []byte{
	0x0a, 0x18, 0x68, 0x61, 0x6d, 0x2d, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2d,
	0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbe, 0x01, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x70,
	0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x22, 0x3b, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f,
	0x6f, 0x6c, 0x12, 0x2b, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65,
	0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ham_questions_pool_proto_rawDescOnce sync.Once
	file_ham_questions_pool_proto_rawDescData = file_ham_questions_pool_proto_rawDesc
)

func file_ham_questions_pool_proto_rawDescGZIP() []byte {
	file_ham_questions_pool_proto_rawDescOnce.Do(func() {
		file_ham_questions_pool_proto_rawDescData = protoimpl.X.CompressGZIP(file_ham_questions_pool_proto_rawDescData)
	})
	return file_ham_questions_pool_proto_rawDescData
}

var file_ham_questions_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ham_questions_pool_proto_goTypes = []interface{}{
	(*Question)(nil),     // 0: proto.Question
	(*QuestionPool)(nil), // 1: proto.QuestionPool
}
var file_ham_questions_pool_proto_depIdxs = []int32{
	0, // 0: proto.QuestionPool.question:type_name -> proto.Question
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ham_questions_pool_proto_init() }
func file_ham_questions_pool_proto_init() {
	if File_ham_questions_pool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ham_questions_pool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ham_questions_pool_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ham_questions_pool_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ham_questions_pool_proto_goTypes,
		DependencyIndexes: file_ham_questions_pool_proto_depIdxs,
		MessageInfos:      file_ham_questions_pool_proto_msgTypes,
	}.Build()
	File_ham_questions_pool_proto = out.File
	file_ham_questions_pool_proto_rawDesc = nil
	file_ham_questions_pool_proto_goTypes = nil
	file_ham_questions_pool_proto_depIdxs = nil
}
