// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: ham-questions-pool.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sublement   string   `protobuf:"bytes,1,opt,name=Sublement,proto3" json:"Sublement,omitempty"` // G0, G1 ,G2
	Section     string   `protobuf:"bytes,2,opt,name=Section,proto3" json:"Section,omitempty"`     // A, B, C
	Sequence    int32    `protobuf:"varint,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`  //
	Chapter     string   `protobuf:"bytes,4,opt,name=Chapter,proto3" json:"Chapter,omitempty"`
	Stem        string   `protobuf:"bytes,5,opt,name=Stem,proto3" json:"Stem,omitempty"`
	Key         string   `protobuf:"bytes,6,opt,name=Key,proto3" json:"Key,omitempty"`
	Distractors []string `protobuf:"bytes,7,rep,name=Distractors,proto3" json:"Distractors,omitempty"`
	Figure      string   `protobuf:"bytes,8,opt,name=Figure,proto3" json:"Figure,omitempty"`
}

func (x *Question) Reset() {
	*x = Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ham_questions_pool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_ham_questions_pool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_ham_questions_pool_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetSublement() string {
	if x != nil {
		return x.Sublement
	}
	return ""
}

func (x *Question) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Question) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Question) GetChapter() string {
	if x != nil {
		return x.Chapter
	}
	return ""
}

func (x *Question) GetStem() string {
	if x != nil {
		return x.Stem
	}
	return ""
}

func (x *Question) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Question) GetDistractors() []string {
	if x != nil {
		return x.Distractors
	}
	return nil
}

func (x *Question) GetFigure() string {
	if x != nil {
		return x.Figure
	}
	return ""
}

type QuestionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*Question `protobuf:"bytes,1,rep,name=Questions,proto3" json:"Questions,omitempty"`
}

func (x *QuestionList) Reset() {
	*x = QuestionList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ham_questions_pool_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionList) ProtoMessage() {}

func (x *QuestionList) ProtoReflect() protoreflect.Message {
	mi := &file_ham_questions_pool_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionList.ProtoReflect.Descriptor instead.
func (*QuestionList) Descriptor() ([]byte, []int) {
	return file_ham_questions_pool_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionList) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type CompleteQuestionPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subl []*Sublement `protobuf:"bytes,1,rep,name=Subl,proto3" json:"Subl,omitempty"` // G1 - G0
}

func (x *CompleteQuestionPool) Reset() {
	*x = CompleteQuestionPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ham_questions_pool_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteQuestionPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteQuestionPool) ProtoMessage() {}

func (x *CompleteQuestionPool) ProtoReflect() protoreflect.Message {
	mi := &file_ham_questions_pool_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteQuestionPool.ProtoReflect.Descriptor instead.
func (*CompleteQuestionPool) Descriptor() ([]byte, []int) {
	return file_ham_questions_pool_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteQuestionPool) GetSubl() []*Sublement {
	if x != nil {
		return x.Subl
	}
	return nil
}

type Sublement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SublementId string                   `protobuf:"bytes,1,opt,name=SublementId,proto3" json:"SublementId,omitempty"`
	GroupMap    map[string]*QuestionList `protobuf:"bytes,2,rep,name=GroupMap,proto3" json:"GroupMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // A, B, C...
}

func (x *Sublement) Reset() {
	*x = Sublement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ham_questions_pool_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sublement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sublement) ProtoMessage() {}

func (x *Sublement) ProtoReflect() protoreflect.Message {
	mi := &file_ham_questions_pool_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sublement.ProtoReflect.Descriptor instead.
func (*Sublement) Descriptor() ([]byte, []int) {
	return file_ham_questions_pool_proto_rawDescGZIP(), []int{3}
}

func (x *Sublement) GetSublementId() string {
	if x != nil {
		return x.SublementId
	}
	return ""
}

func (x *Sublement) GetGroupMap() map[string]*QuestionList {
	if x != nil {
		return x.GroupMap
	}
	return nil
}

var File_ham_questions_pool_proto protoreflect.FileDescriptor

var file_ham_questions_pool_proto_rawDesc = []byte{
	0x0a, 0x18, 0x68, 0x61, 0x6d, 0x2d, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2d,
	0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xd8, 0x01, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x53, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x53, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x74, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x74, 0x65, 0x6d,
	0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b,
	0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72,
	0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x69, 0x73, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x69, 0x67, 0x75, 0x72, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x46, 0x69, 0x67, 0x75, 0x72, 0x65, 0x22, 0x3d, 0x0a, 0x0c,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x09,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x09, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3c, 0x0a, 0x14, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x50,
	0x6f, 0x6f, 0x6c, 0x12, 0x24, 0x0a, 0x04, 0x53, 0x75, 0x62, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x04, 0x53, 0x75, 0x62, 0x6c, 0x22, 0xbb, 0x01, 0x0a, 0x09, 0x53, 0x75,
	0x62, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x53, 0x75,
	0x62, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x08, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x61, 0x70, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x4d, 0x61, 0x70, 0x1a, 0x50, 0x0a, 0x0d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61,
	0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ham_questions_pool_proto_rawDescOnce sync.Once
	file_ham_questions_pool_proto_rawDescData = file_ham_questions_pool_proto_rawDesc
)

func file_ham_questions_pool_proto_rawDescGZIP() []byte {
	file_ham_questions_pool_proto_rawDescOnce.Do(func() {
		file_ham_questions_pool_proto_rawDescData = protoimpl.X.CompressGZIP(file_ham_questions_pool_proto_rawDescData)
	})
	return file_ham_questions_pool_proto_rawDescData
}

var file_ham_questions_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ham_questions_pool_proto_goTypes = []interface{}{
	(*Question)(nil),             // 0: proto.Question
	(*QuestionList)(nil),         // 1: proto.QuestionList
	(*CompleteQuestionPool)(nil), // 2: proto.CompleteQuestionPool
	(*Sublement)(nil),            // 3: proto.Sublement
	nil,                          // 4: proto.Sublement.GroupMapEntry
}
var file_ham_questions_pool_proto_depIdxs = []int32{
	0, // 0: proto.QuestionList.Questions:type_name -> proto.Question
	3, // 1: proto.CompleteQuestionPool.Subl:type_name -> proto.Sublement
	4, // 2: proto.Sublement.GroupMap:type_name -> proto.Sublement.GroupMapEntry
	1, // 3: proto.Sublement.GroupMapEntry.value:type_name -> proto.QuestionList
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ham_questions_pool_proto_init() }
func file_ham_questions_pool_proto_init() {
	if File_ham_questions_pool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ham_questions_pool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ham_questions_pool_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ham_questions_pool_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteQuestionPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ham_questions_pool_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sublement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ham_questions_pool_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ham_questions_pool_proto_goTypes,
		DependencyIndexes: file_ham_questions_pool_proto_depIdxs,
		MessageInfos:      file_ham_questions_pool_proto_msgTypes,
	}.Build()
	File_ham_questions_pool_proto = out.File
	file_ham_questions_pool_proto_rawDesc = nil
	file_ham_questions_pool_proto_goTypes = nil
	file_ham_questions_pool_proto_depIdxs = nil
}
