// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: proto/ham-questions-pool.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Question struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subelement  string   `protobuf:"bytes,1,opt,name=Subelement,proto3" json:"Subelement,omitempty"` // G0, G1 ,G2
	Group       string   `protobuf:"bytes,2,opt,name=Group,proto3" json:"Group,omitempty"`           // A, B, C
	Sequence    int32    `protobuf:"varint,3,opt,name=Sequence,proto3" json:"Sequence,omitempty"`    // 01, 02
	Chapter     string   `protobuf:"bytes,4,opt,name=Chapter,proto3" json:"Chapter,omitempty"`
	Stem        string   `protobuf:"bytes,5,opt,name=Stem,proto3" json:"Stem,omitempty"`
	Key         string   `protobuf:"bytes,6,opt,name=Key,proto3" json:"Key,omitempty"`
	Distractors []string `protobuf:"bytes,7,rep,name=Distractors,proto3" json:"Distractors,omitempty"`
	Figure      string   `protobuf:"bytes,8,opt,name=Figure,proto3" json:"Figure,omitempty"`
}

func (x *Question) Reset() {
	*x = Question{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ham_questions_pool_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ham_questions_pool_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_proto_ham_questions_pool_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetSubelement() string {
	if x != nil {
		return x.Subelement
	}
	return ""
}

func (x *Question) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Question) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Question) GetChapter() string {
	if x != nil {
		return x.Chapter
	}
	return ""
}

func (x *Question) GetStem() string {
	if x != nil {
		return x.Stem
	}
	return ""
}

func (x *Question) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Question) GetDistractors() []string {
	if x != nil {
		return x.Distractors
	}
	return nil
}

func (x *Question) GetFigure() string {
	if x != nil {
		return x.Figure
	}
	return ""
}

type QuestionList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*Question `protobuf:"bytes,1,rep,name=Questions,proto3" json:"Questions,omitempty"`
}

func (x *QuestionList) Reset() {
	*x = QuestionList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ham_questions_pool_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuestionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionList) ProtoMessage() {}

func (x *QuestionList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ham_questions_pool_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionList.ProtoReflect.Descriptor instead.
func (*QuestionList) Descriptor() ([]byte, []int) {
	return file_proto_ham_questions_pool_proto_rawDescGZIP(), []int{1}
}

func (x *QuestionList) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type CompleteQuestionPool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubelementMap map[string]*Subelement `protobuf:"bytes,1,rep,name=SubelementMap,proto3" json:"SubelementMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *CompleteQuestionPool) Reset() {
	*x = CompleteQuestionPool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ham_questions_pool_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteQuestionPool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteQuestionPool) ProtoMessage() {}

func (x *CompleteQuestionPool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ham_questions_pool_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteQuestionPool.ProtoReflect.Descriptor instead.
func (*CompleteQuestionPool) Descriptor() ([]byte, []int) {
	return file_proto_ham_questions_pool_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteQuestionPool) GetSubelementMap() map[string]*Subelement {
	if x != nil {
		return x.SubelementMap
	}
	return nil
}

type Group struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string      `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"` // A B C D
	Title     string      `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Questions []*Question `protobuf:"bytes,3,rep,name=Questions,proto3" json:"Questions,omitempty"` // 01 02 03
}

func (x *Group) Reset() {
	*x = Group{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ham_questions_pool_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ham_questions_pool_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_proto_ham_questions_pool_proto_rawDescGZIP(), []int{3}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Group) GetQuestions() []*Question {
	if x != nil {
		return x.Questions
	}
	return nil
}

type Subelement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string            `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"` // G1 - G0
	Title    string            `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	GroupMap map[string]*Group `protobuf:"bytes,3,rep,name=GroupMap,proto3" json:"GroupMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // A, B, C...
}

func (x *Subelement) Reset() {
	*x = Subelement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ham_questions_pool_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Subelement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subelement) ProtoMessage() {}

func (x *Subelement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ham_questions_pool_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subelement.ProtoReflect.Descriptor instead.
func (*Subelement) Descriptor() ([]byte, []int) {
	return file_proto_ham_questions_pool_proto_rawDescGZIP(), []int{4}
}

func (x *Subelement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subelement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Subelement) GetGroupMap() map[string]*Group {
	if x != nil {
		return x.GroupMap
	}
	return nil
}

// just titles
type AllTitles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subelements []*SubelementTitle `protobuf:"bytes,1,rep,name=Subelements,proto3" json:"Subelements,omitempty"`
}

func (x *AllTitles) Reset() {
	*x = AllTitles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ham_questions_pool_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllTitles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTitles) ProtoMessage() {}

func (x *AllTitles) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ham_questions_pool_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTitles.ProtoReflect.Descriptor instead.
func (*AllTitles) Descriptor() ([]byte, []int) {
	return file_proto_ham_questions_pool_proto_rawDescGZIP(), []int{5}
}

func (x *AllTitles) GetSubelements() []*SubelementTitle {
	if x != nil {
		return x.Subelements
	}
	return nil
}

type SubelementTitle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string        `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Groups []*GroupTitle `protobuf:"bytes,3,rep,name=Groups,proto3" json:"Groups,omitempty"`
}

func (x *SubelementTitle) Reset() {
	*x = SubelementTitle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ham_questions_pool_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubelementTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubelementTitle) ProtoMessage() {}

func (x *SubelementTitle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ham_questions_pool_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubelementTitle.ProtoReflect.Descriptor instead.
func (*SubelementTitle) Descriptor() ([]byte, []int) {
	return file_proto_ham_questions_pool_proto_rawDescGZIP(), []int{6}
}

func (x *SubelementTitle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubelementTitle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SubelementTitle) GetGroups() []*GroupTitle {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GroupTitle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *GroupTitle) Reset() {
	*x = GroupTitle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ham_questions_pool_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupTitle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTitle) ProtoMessage() {}

func (x *GroupTitle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ham_questions_pool_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTitle.ProtoReflect.Descriptor instead.
func (*GroupTitle) Descriptor() ([]byte, []int) {
	return file_proto_ham_questions_pool_proto_rawDescGZIP(), []int{7}
}

func (x *GroupTitle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupTitle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_proto_ham_questions_pool_proto protoreflect.FileDescriptor

var file_proto_ham_questions_pool_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x6d, 0x2d, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x70, 0x6f, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd6, 0x01, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x65, 0x6c, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x53, 0x75, 0x62, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x53, 0x65,
	0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x43, 0x68, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x74, 0x65, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x53, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x69, 0x67, 0x75,
	0x72, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x46, 0x69, 0x67, 0x75, 0x72, 0x65,
	0x22, 0x3d, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x2d, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0xc1, 0x01, 0x0a, 0x14, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x51, 0x75, 0x65, 0x73,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x12, 0x54, 0x0a, 0x0d, 0x53, 0x75, 0x62, 0x65,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x6f, 0x6c, 0x2e, 0x53, 0x75, 0x62,
	0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x0d, 0x53, 0x75, 0x62, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x1a, 0x53,
	0x0a, 0x12, 0x53, 0x75, 0x62, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x61, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75,
	0x62, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x5c, 0x0a, 0x05, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x51, 0x75,
	0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0xba, 0x01, 0x0a, 0x0a, 0x53, 0x75, 0x62, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d,
	0x61, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x75, 0x62, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x4d, 0x61, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x4d, 0x61, 0x70, 0x1a, 0x49, 0x0a, 0x0d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x61, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x45,
	0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x12, 0x38, 0x0a, 0x0b, 0x53,
	0x75, 0x62, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x75, 0x62, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x0b, 0x53, 0x75, 0x62, 0x65, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x62, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x65, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x29,
	0x0a, 0x06, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x52, 0x06, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0x32, 0x0a, 0x0a, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x42, 0x3a, 0x5a,
	0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x75, 0x6c, 0x75,
	0x6d, 0x65, 0x6c, 0x30, 0x6e, 0x2f, 0x61, 0x72, 0x72, 0x6c, 0x2d, 0x68, 0x61, 0x6d, 0x2d, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x70, 0x6f, 0x6f, 0x6c, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_ham_questions_pool_proto_rawDescOnce sync.Once
	file_proto_ham_questions_pool_proto_rawDescData = file_proto_ham_questions_pool_proto_rawDesc
)

func file_proto_ham_questions_pool_proto_rawDescGZIP() []byte {
	file_proto_ham_questions_pool_proto_rawDescOnce.Do(func() {
		file_proto_ham_questions_pool_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ham_questions_pool_proto_rawDescData)
	})
	return file_proto_ham_questions_pool_proto_rawDescData
}

var file_proto_ham_questions_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_ham_questions_pool_proto_goTypes = []interface{}{
	(*Question)(nil),             // 0: proto.Question
	(*QuestionList)(nil),         // 1: proto.QuestionList
	(*CompleteQuestionPool)(nil), // 2: proto.CompleteQuestionPool
	(*Group)(nil),                // 3: proto.Group
	(*Subelement)(nil),           // 4: proto.Subelement
	(*AllTitles)(nil),            // 5: proto.AllTitles
	(*SubelementTitle)(nil),      // 6: proto.SubelementTitle
	(*GroupTitle)(nil),           // 7: proto.GroupTitle
	nil,                          // 8: proto.CompleteQuestionPool.SubelementMapEntry
	nil,                          // 9: proto.Subelement.GroupMapEntry
}
var file_proto_ham_questions_pool_proto_depIdxs = []int32{
	0, // 0: proto.QuestionList.Questions:type_name -> proto.Question
	8, // 1: proto.CompleteQuestionPool.SubelementMap:type_name -> proto.CompleteQuestionPool.SubelementMapEntry
	0, // 2: proto.Group.Questions:type_name -> proto.Question
	9, // 3: proto.Subelement.GroupMap:type_name -> proto.Subelement.GroupMapEntry
	6, // 4: proto.AllTitles.Subelements:type_name -> proto.SubelementTitle
	7, // 5: proto.SubelementTitle.Groups:type_name -> proto.GroupTitle
	4, // 6: proto.CompleteQuestionPool.SubelementMapEntry.value:type_name -> proto.Subelement
	3, // 7: proto.Subelement.GroupMapEntry.value:type_name -> proto.Group
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_ham_questions_pool_proto_init() }
func file_proto_ham_questions_pool_proto_init() {
	if File_proto_ham_questions_pool_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ham_questions_pool_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Question); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ham_questions_pool_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuestionList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ham_questions_pool_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteQuestionPool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ham_questions_pool_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Group); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ham_questions_pool_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Subelement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ham_questions_pool_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllTitles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ham_questions_pool_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubelementTitle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ham_questions_pool_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupTitle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ham_questions_pool_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_ham_questions_pool_proto_goTypes,
		DependencyIndexes: file_proto_ham_questions_pool_proto_depIdxs,
		MessageInfos:      file_proto_ham_questions_pool_proto_msgTypes,
	}.Build()
	File_proto_ham_questions_pool_proto = out.File
	file_proto_ham_questions_pool_proto_rawDesc = nil
	file_proto_ham_questions_pool_proto_goTypes = nil
	file_proto_ham_questions_pool_proto_depIdxs = nil
}
